### ISSUE TITLE
Equality elimination appears to be broken

### ISSUE THREAD

**Issue by esotechnica** [OpenLogicProject/fitch-checker#6] opened 2018-01-12 12:22 UTC
See details at the following link:

https://math.stackexchange.com/questions/2601281/whats-wrong-with-this-proof-of-symmetry-of-equality/2602046#2602046

**Comment by rzach** [comment] 2018-01-12 16:12
Confirmed also on Kevin's original. It's not a stable bug; works most of the time.

![screenshot from 2018-01-12 08-49-50](https://user-images.githubusercontent.com/3122348/34883965-82cfd948-f778-11e7-85c0-e5b09cafd183.png)
![screenshot from 2018-01-12 09-07-28](https://user-images.githubusercontent.com/3122348/34883954-7ad8d136-f778-11e7-9f8e-daf7ce782fcd.png)
![screenshot from 2018-01-12 08-53-03](https://user-images.githubusercontent.com/3122348/34883971-8646c7ee-f778-11e7-9bbd-f13219e79b5e.png)
![screenshot from 2018-01-12 08-50-46](https://user-images.githubusercontent.com/3122348/34883975-8973bd78-f778-11e7-857d-0fe154c3ad6e.png)

**Comment by frabjous** [comment] 2018-01-12 16:14
Richard,

I fixed this bug and committed the change to the repo. But you'll need to
implement the change to where you have the demo on the website.

-Kevin

**Comment by frabjous** [comment] 2018-01-12 16:18
Incidentally, the problem was not with =E, but with sameWff as applied to identity statements. Not worth trying to explain here.

**Comment by rzach** [comment] 2018-01-12 16:33
Thanks @frabjous Fixed in 6b21373f0d08853715b18726122b54695a0179df

**Closed as completed by rzach** 2018-01-12 16:33 UTC
Labels: bug

**Comment by rzach** [comment] 2018-01-12 16:34
(The fix is live on the website too)
